### ISSUE TITLE
Could not initialize project - aarch64

### ISSUE THREAD

**Issue by saulomeirelles** [platformio/platformio-home#1989] opened 2020-12-31 18:57 UTC
I am not able to use Kendryte210 on aarch64. Is there any support for this architecture?

PIO Core Call Error: [...] Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Could not find the package with 'platformio/toolchain-kendryte210 @ ~8.2.0' requirements for your system 'linux_aarch64'"

**Comment by ivankravets** [comment] 2021-01-26 14:37
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:37 UTC
