### ISSUE TITLE
Could not initialize project for Heltec LoRa board

### ISSUE THREAD

**Issue by B1td0g** [platformio/platformio-home#162] opened 2019-12-07 17:28 UTC
Hi there,

I am trying to create a project for a Heltec Lora V2 board (the exact name on the board list is Heltec Wifi LoRa 32 (V2) (Heltec Automation)) and it seems that when trying to create the project, Platform IO cannot find the actual board file. Seems to be a naming issue (see the end of the error message). 

I am using Visual Studio Code with the latest Platform IO on a Mac OS Mojave.

PIO Core Call Error: "The current working directory /Users/xxxx/Documents/PlatformIO/Projects/LoraTest will be used for the project.\n\nThe next files/directories have been created in /Users/xxxx/Documents/PlatformIO/Projects/LoraTest\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing heltec_wifi_lora_32_V2 (platform: espressif32; board: heltec_wifi_lora_32_V2; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'heltec_wifi_lora_32_V2'\n========================== [FAILED] Took 0.39 seconds =========================="

**Comment by ivankravets** [comment] 2020-02-29 17:15
Duplicate of https://github.com/platformio/platformio-home/issues/155

**Closed by ivankravets** 2020-02-29 17:15 UTC
