### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by 03sarath** [platformio/platformio-home#326] opened 2020-01-24 05:07 UTC
I'm looking forward to **MKRWAN 1310 Board** in PlatformIO.But I'm disappointed with this issue. Please let know can I resolve this issue.

PIO Core Call Error: "The current working directory C:\\Users\\ADMIN\\Documents\\PlatformIO\\Projects\\MKRWAN_WORDWRAP8 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\ADMIN\\Documents\\PlatformIO\\Projects\\MKRWAN_WORDWRAP8\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Unknown board ID 'mkrwan1310'"

**Comment by ivankravets** [comment] 2020-02-29 17:17
Duplicate of https://github.com/platformio/platformio-home/issues/155

**Closed by ivankravets** 2020-02-29 17:17 UTC
