### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by G3ZQC** [platformio/platformio-home#2001] opened 2021-01-02 11:31 UTC
PIO Core Call Error: "Platform Manager: Installing git+https://github.com/sipeed/platform-gd32v.git\r\n\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 332, in platform_install\r\n    force=force,\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\platform.py\", line 49, in install\r\n    spec, silent=silent, force=force, skip_dependencies=True\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\_install.py\", line 49, in install\r\n    spec, silent=silent, skip_dependencies=skip_dependencies, force=force\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\_install.py\", line 97, in _install\r\n    pkg = self.install_from_url(spec.url, spec, silent=silent)\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\_install.py\", line 141, in install_from_url\r\n    vcs = VCSClientFactory.new(tmp_dir, url)\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\vcsclient.py\", line 55, in new\r\n    src_dir, remote_url, tag, silent\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\vcsclient.py\", line 137, in __init__\r\n    self.configure()\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\vcsclient.py\", line 146, in configure\r\n    result = proc.exec_command([cls.command, \"--exec-path\"])\r\n  File \"c:\\users\\jim\\.platformio\\penv\\lib\\site-packages\\platformio\\proc.py\", line 113, in exec_command\r\n    p = subprocess.Popen(*args, **kwargs)\r\n  File \"C:\\Users\\Jim\\.platformio\\python3\\lib\\subprocess.py\", line 800, in __init__\r\n    restore_signals, start_new_session)\r\n  File \"C:\\Users\\Jim\\.platformio\\python3\\lib\\subprocess.py\", line 1207, in _execute_child\r\n    startupinfo)\r\nFileNotFoundError: [WinError 2] The system cannot find the file specified\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment] 2021-01-26 14:35
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Closed by ivankravets** 2021-01-26 14:35 UTC
