### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by 1Speedi1** [platformio/platformio-home#2124] opened 2021-01-20 11:54 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Kenneth Wermuth\\.platformio\\platforms\\atmelavr metadata=PackageMetaData <type=platform name=atmelavr version=3.1.0 spec={'owner': 'platformio', 'id': 8006, 'name': 'atmelavr', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:42
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:42 UTC

**Comment by 1Speedi1** [comment] 2021-01-21 09:27
> Duplicate of #2123
> 
> Could you provide more details on how to reproduce this issue?

Sorry, Iam new, so did not know I posted it in forum.  
It came up when I tried to select board, so could not select any board.
