### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by VereNicolson** [platformio/platformio-home#108] opened 2019-11-23 03:05 UTC
PIO Core Call Error: "Library Storage: C:\\Users\\vere.nicolson\\.platformio\\lib\nUpdating SD                              @ 1.2.3          [1.2.4]\r\nUninstalling SD @ 1.2.3: \t[OK]\nLooking for SD library in registry\nSD\r\n==\n#ID: 161\nThis library aims to expose a subset of SD card functionality in the form of a higher level 'wrapper' object\r\n\r\nKeywords: sd, card, file, system\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR\r\nAuthors: Adafruit Industries\r\n\r\nSD\r\n==\n#ID: 868\nEnables reading and writing on SD cards.\r\n\r\nKeywords: storage, data\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, GigaDevice GD32V, Infineon XMC, Intel ARC32, Kendryte K210, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, ST STM8, Teensy, TI MSP430\r\nAuthors: Arduino, SparkFun\r\n\r\nSD\r\n==\n#ID: 79\nThis library aims to expose a subset of SD card functionality in the form of a higher level 'wrapper' object (adaptation for LaunchPad LM4F120 / TM4C123)\r\n\r\nKeywords: sd, card, file, system\r\nCompatible frameworks: Energia\r\nCompatible platforms: TI MSP430, TI TIVA\r\nAuthors: Rei Vilo, William Greiman, SparkFun Electronics\r\n\r\nSD\r\n==\n#ID: 5210\nSD\r\n\r\nKeywords: sd\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Jackson Lv\r\n\r\nFound: https://platformio.org/lib/show/161/SD\nLibraryManager: Installing id=161 @ 1.2.4\r\n\n\nConflict: More than one library has been found by request {\"requirements\": \"1.2.4\", \"name\": \"SD\"}:\nAutomatically chose the first available library (use `--interactive` option to make a choice)\nError: Could not find a version that satisfies the requirement '1.2.4' for your system 'windows_amd64'"

**Comment by ivankravets** [comment] 2019-11-25 17:54
Duplicate of https://github.com/platformio/platformio-core/issues/3149

**Closed by ivankravets** 2019-11-25 17:54 UTC
