### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Moda-cmd** [platformio/platformio-home#388] opened 2020-02-12 03:59 UTC
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\karol\\\\OneDrive\\\\Documents\\\\PlatformIO'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment] 2020-02-29 16:59
Duplicate of https://github.com/platformio/platformio-home/issues/408

**Closed by ivankravets** 2020-02-29 16:59 UTC
