### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by Spider84** [platformio/platformio-home#1891] opened 2020-12-16 05:50 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\spide\\.platformio\\platforms\\ststm32@9.0.0 metadata=PackageMetaData <type=platform name=ststm32 version=9.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:47
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:47 UTC

**Comment by LucaPon** [comment] 2021-02-02 23:57
Having the same problem, I tried to reinstall PlatformIO extension and to delete files in `%USERPROFILE%\.vscode\extensions` but it didn't help. The problem occurs when I click on "New project" in "PIO Home", when I open "Platforms" or "Boards" sections or when I click on "Updates"->"Platform Updates".

`Error: Unknown development platform 'PackageItem <path=C:\Users\Luca\.platformio\platforms\ststm32 metadata=PackageMetaData <type=platform name=ststm32 version=9.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'`
