### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by fromCologne** [platformio/platformio-home#1824] opened 2020-12-06 06:54 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Ingo\\.platformio\\platforms\\espressif32@2.0.0 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:48
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:48 UTC
