### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by tomacaster** [platformio/platformio-home#2086] opened 2021-01-16 16:45 UTC
PIO Core Call Error: "The current working directory /home/michal/Documents/PlatformIO/Projects/WatchESP will be used for the project.\n\nThe next files/directories have been created in /home/michal/Documents/PlatformIO/Projects/WatchESP\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing ttgo-t-watch (platform: espressif32; board: ttgo-t-watch; framework: espidf)\n--------------------------------------------------------------------------------\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80200.0\nTool Manager: toolchain-xtensa32 @ 2.80200.200827 has been installed!\nTool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0\nTool Manager: toolchain-esp32ulp @ 1.22851.191205 has been installed!\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\nTool Manager: Installing platformio/tool-cmake @ ~3.16.0\nTool Manager: tool-cmake @ 3.16.4 has been installed!\nTool Manager: Installing platformio/tool-ninja @ ^1.7.0\nTool Manager: tool-ninja @ 1.7.1 has been installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/ttgo-t-watch.html\nPLATFORM: Espressif 32 (2.1.0) > TTGO T-Watch\nHARDWARE: ESP32 240MHz, 320KB RAM, 16MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40100.200827 (4.1.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.30000.201119 (3.0.0) \n - tool-ninja 1.7.1 \n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \n - toolchain-xtensa32 2.80200.200827 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nCollecting cryptography>=2.1.4\n  Using cached cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)\nCollecting future>=0.15.2\n  Using cached future-0.18.2-py3-none-any.whl\nCollecting pyparsing<2.4.0,>=2.0.3\n  Using cached pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\nCollecting cffi>=1.12\n  Using cached cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl (411 kB)\nCollecting six>=1.4.1\n  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)\nCollecting pycparser\n  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)\nInstalling collected packages: pycparser, six, cffi, pyparsing, future, cryptography\nSuccessfully installed cffi-1.14.4 cryptography-3.3.1 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 six-1.15.0\nReading CMake configuration...\nAssertionError: :\n  File \"/home/michal/.platformio/penv/lib/python3.8/site-packages/platformio/builder/main.py\", line 170:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 598:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 287:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/home/michal/.platformio/platforms/espressif32/builder/main.py\", line 224:\n    target_elf = env.BuildProgram()\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/home/michal/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/platformio.py\", line 61:\n    env.ProcessProgramDeps()\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/home/michal/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/platformio.py\", line 127:\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/home/michal/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/platformio.py\", line 342:\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 661:\n    return method(*args, **kw)\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 598:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/home/michal/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 287:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/home/michal/.platformio/platforms/espressif32/builder/frameworks/espidf.py\", line 1177:\n    ota_partition_params = get_partition_info(\n  File \"/home/michal/.platformio/platforms/espressif32/builder/frameworks/espidf.py\", line 838:\n    assert os.path.isfile(pt_path)\n========================= [FAILED] Took 60.36 seconds ========================="

**Comment by ivankravets** [comment] 2021-01-26 12:54
Duplicate of https://github.com/platformio/platform-espressif32/issues/476

**Closed by ivankravets** 2021-01-26 12:54 UTC
