### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by TxBillbr** [platformio/platformio-home#2051] opened 2021-01-09 17:09 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Bill\\.platformio\\platforms\\espressif32@2.0.0 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by TxBillbr** [comment] 2021-01-09 17:11
Created by navigating to platforms from Home, clicking updates and clicking all needed updates.

**Comment by ivankravets** [comment] 2021-01-20 13:42
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed** 2021-01-20 13:49 UTC
