### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by rmclean530** [platformio/platformio-home#1831] opened 2020-12-07 03:52 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Victoria\\.platformio\\platforms\\atmelsam metadata=PackageMetaData <type=platform name=atmelsam version=5.0.1 spec={'owner': 'platformio', 'id': 8007, 'name': 'atmelsam', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:49
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:49 UTC

**Comment by rmclean530** [comment] 2021-01-22 02:04
Yeah computer just wouldn't load the boards file I could never get the
visual studio program to work rite on that computer
