### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by knst885** [platformio/platformio-home#2085] opened 2021-01-15 19:04 UTC
PIO Core Call Error: "Platform Manager: Installing st stm32\r\n\n\nError: Could not find the package with 'st stm32' requirements for your system 'windows_x86'"

**Comment by ivankravets** [comment] 2021-01-26 14:37
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:37 UTC
