### ISSUE TITLE
Libraries: Builtin

### ISSUE THREAD

**Issue by legionaryu** [platformio/platformio-home#24] opened 2019-10-28 20:53 UTC
If I click into the PIO Home/Libraries/Builtin it crashes with the following error:
> TypeError: Cannot read property 'map' of undefined
>     at t.value (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:18:213524)
>     at Zi (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:70772)
>     at Ji (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:70567)
>     at Ds (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:105897)
>     at kl (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:90221)
>     at Rl (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:90146)
>     at El (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:87486)
>     at http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:45816
>     at t.unstable_runWithPriority (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:42:3465)
>     at Ka (http://127.0.0.1:8010/b53d63f92df2c62861fd.min.js:34:45525)

I'm using Visual Studio Code Insiders:
> Version: 1.40.0-insider (system setup)
> Commit: 33cc09da7a314ea0ee5677d1927739af60d16734
> Date: 2019-10-28T11:50:41.596Z
> Electron: 6.1.2
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Windows_NT x64 10.0.17763

**Comment by pfeerick** [comment] 2019-10-29 05:34
Error message looks supiciously similar to that of #23 ... possibly related?

**Comment by ivankravets** [comment] 2019-11-01 15:45
Duplicate of https://github.com/platformio/platformio-home/issues/23

**Closed by ivankravets** 2019-11-01 15:45 UTC

**Comment by ivankravets** [comment] 2019-11-01 15:56
This is actually a bug, I reproduced it. Thanks!
