### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by Artem4ik05** [platformio/platformio-home#1771] opened 2020-11-28 09:55 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\avarv\\.platformio\\platforms\\ststm32@8.1.0 metadata=PackageMetaData <type=platform name=ststm32 version=8.1.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:48
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:48 UTC
