### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by dmarirs** [platformio/platformio-home#1747] opened 2020-11-23 00:59 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\dmari\\.platformio\\platforms\\espressif32 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:48
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:48 UTC
