### ISSUE TITLE
Could not list directory/Users/dante/Documents/PlatformIO/Projects

### ISSUE THREAD

**Issue by Dormey** [platformio/platformio-home#149] opened 2019-12-02 00:17 UTC
Server error: {"args":[1,"Operation not permitted"],"message":"[Errno 1] Operation not permitted: '/Users/dante/Documents/PlatformIO/Projects'","type":"OSError"}

**Comment by ivankravets** [comment] 2019-12-02 11:40
Duplicate of https://github.com/platformio/platformio-home/issues/54

**Closed by ivankravets** 2019-12-02 11:40 UTC
