### ISSUE TITLE
Could not load platform updates

### ISSUE THREAD

**Issue by riatankarsahu** [platformio/platformio-home#2027] opened 2021-01-05 21:49 UTC
PIO Core Call Error: "b''\n\nError: Unknown development platform 'PackageItem <path=C:\\Users\\Anticitizen\\.platformio\\platforms\\espressif32@2.0.0 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:43
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:43 UTC
