### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by cwl0127** [platformio/platformio-home#1784] opened 2020-12-01 09:36 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Administrator\\.platformio\\platforms\\ststm32 metadata=PackageMetaData <type=platform name=ststm32 version=10.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:48
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:48 UTC
