### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by Rodpais** [platformio/platformio-home#2141] opened 2021-01-21 21:20 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\rodri\\.platformio\\platforms\\ststm32 metadata=PackageMetaData <type=platform name=ststm32 version=11.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-22 21:24
Could you provide more details on how to reproduce this issue?

**Comment by ivankravets** [comment] 2021-01-26 13:00
Duplicate of https://github.com/platformio/platformio-home/issues/2123

**Closed by ivankravets** 2021-01-26 13:00 UTC
