### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by tianzehao** [platformio/platformio-home#2055] opened 2021-01-10 07:18 UTC
PIO Core Call Error: "Platform Manager: Installing espressif8266\r\n\n\nError: HTTPSConnectionPool(host='dl.registry.platformio.org', port=443): Max retries exceeded with url: /download/platformio/platform/espressif8266/2.6.2/espressif8266-2.6.2.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027EFAF3F108>, 'Connection to dl.registry.platformio.org timed out. (connect timeout=10)'))"

**Comment by ivankravets** [comment] 2021-01-26 17:57
Duplicate of https://github.com/platformio/platformio-core/issues/1348

**Closed by ivankravets** 2021-01-26 17:57 UTC
