### ISSUE TITLE
Could not list directory/home/jonathan/Downloads

### ISSUE THREAD

**Issue by jonathanbachsantos** [platformio/platformio-home#104] opened 2019-11-22 11:48 UTC
'utf-8' codec can't encode character '\udc88' in position 125: surrogates not allowed

**Comment by ivankravets** [comment] 2019-11-25 17:56
What is your OS? `python --version`?

**Comment by ivankravets** [comment] 2019-11-25 17:56
Duplicate of https://github.com/platformio/platformio-home/issues/75

**Closed by ivankravets** 2019-11-25 17:56 UTC
