### ISSUE TITLE
Libraries: Builtin

### ISSUE THREAD

**Issue by aksiihtiyar** [platformio/platformio-home#1888] opened 2020-12-15 19:46 UTC
PIO Core Call Error: "b''\n\nError: Unknown development platform 'PackageItem <path=C:\\Users\\recai\\.platformio\\platforms\\espressif32 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:47
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:47 UTC
