### ISSUE TITLE
DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Patrekur** [platformio/platformio-home#1624] opened 2020-11-02 21:55 UTC
PIO Core Call Error: "DLL load failed: The specified procedure could not be found."
I am unable to create a project in VSCode at all. With or without the PlatformIO extension. 

Edit1. 
I was not sure what additional info was needed but here it is: 
PIO system info:

PlatformIO Core             5.0.2
Python                      3.7.7-final.0
System Type                 windows_amd64
Platform                    Windows-10
File System Encoding        utf-8
Locale Encoding             cp1252
PlatformIO Core Directory   C:\Users\patre\.platformio
PlatformIO Core Executable  C:\Users\patre\.platformio\penv\Scripts\platformio.exe
Python Executable           c:\users\patre\.platformio\penv\scripts\python.exe
Global Libraries            0
Development Platforms       0
Tools & Toolchains          2

**Comment by ivankravets** [comment] 2020-11-03 13:39
Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type 
```
pio system info
```

Please share the output here.

**Comment by ivankravets** [comment] 2020-12-02 16:08
Duplicate of https://github.com/platformio/platformio-home/issues/1772

**Closed by ivankravets** 2020-12-02 16:08 UTC
Labels: help wanted
