### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by elvathck** [platformio/platformio-home#1925] opened 2020-12-21 18:12 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\elvathck\\.platformio\\platforms\\ststm32@8.1.0 metadata=PackageMetaData <type=platform name=ststm32 version=8.1.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by LennartArendt** [comment] 2020-12-23 12:27
Just had the same problem, just with a different platform, try deleting the platform folder and hit build again. 
For me it installed the platform again and everything worked!

**Comment by ivankravets** [comment] 2021-01-20 13:46
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:46 UTC
