### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by tgbrown1687** [platformio/platformio-home#419] opened 2020-02-21 15:47 UTC
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: '/Users/Terry/.platformio/platforms/ESP3DLib/platform.json'","type":"IOError"}

I keep getting the above error while opening VSC or try to install any Library

**Comment by tgbrown1687** [comment] 2020-02-21 15:51
The error post when VCS try's to load recent projects, is there a way to clear recent projects?

**Comment by ivankravets** [comment] 2020-02-29 17:21
Duplicate of https://github.com/platformio/platformio-home/issues/408

**Closed by ivankravets** 2020-02-29 17:21 UTC
