### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by Nikolas3208** [platformio/platformio-home#2140] opened 2021-01-21 18:36 UTC
PIO Core Call Error: "Platform Manager: Installing arduino\r\n\n\nError: Could not find the package with 'arduino' requirements for your system 'windows_x86'"

**Comment by ivankravets** [comment] 2021-01-26 14:37
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:37 UTC
