### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by vortex314** [platformio/platformio-home#1970] opened 2020-12-28 10:30 UTC
PIO Core Call Error: "The current working directory /Users/lieven/Documents/PlatformIO/Projects/f411 will be used for the project.\n\nThe next files/directories have been created in /Users/lieven/Documents/PlatformIO/Projects/f411\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'genericSTM32F411CE'"

**Comment by ivankravets** [comment] 2021-01-26 15:09
Duplicate of https://github.com/platformio/platformio-home/issues/1768

**Closed by ivankravets** 2021-01-26 15:09 UTC
