### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by iamjosegoes** [platformio/platformio-home#198] opened 2019-12-22 00:35 UTC
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\jose.goes\\\\.platformio\\\\platforms\\\\pio-framework-arduino-lpc176x\\\\platform.json'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment] 2020-02-29 16:59
Duplicate of https://github.com/platformio/platformio-home/issues/408

**Closed by ivankravets** 2020-02-29 16:59 UTC
