### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by yoyoh76** [platformio/platformio-home#2059] opened 2021-01-10 21:15 UTC
PIO Core Call Error: "Platform Manager: Installing file://I:\\makers\\PlatformIO\\ESPAsyncWebServer-2.0.0\r\n\n\nError: Could not find one of 'platform.json' manifest files in the package"

**Comment by ivankravets** [comment] 2021-01-26 14:14
Duplicate of https://github.com/platformio/platformio-home/issues/1785

**Closed by ivankravets** 2021-01-26 14:14 UTC
