### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by robocezeri** [platformio/platformio-home#2054] opened 2021-01-10 04:41 UTC
PIO Core Call Error: "Platform Manager: Installing https://github.com/platformio/platformio-home/archive/v3.3.1.zip\r\n\n\nError: Could not find one of 'platform.json' manifest files in the package"

**Comment by ivankravets** [comment] 2021-01-26 14:14
Duplicate of https://github.com/platformio/platformio-home/issues/1785

**Closed by ivankravets** 2021-01-26 14:14 UTC
