### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by brunohorta82** [platformio/platformio-home#53] opened 2019-11-11 11:14 UTC
PIO Core Call Error: "Library Storage: /Users/brunohorta/COMMUNITY/BH-Easy-Iot/EasyIot7/.pio/libdeps/esp12e\nUpdating ESP Async WebServer             @ 2f37037        [f13685e]\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment] 2019-11-11 21:42
Duplicate of https://github.com/platformio/platformio-core/issues/3033

**Closed by ivankravets** 2019-11-11 21:42 UTC
