### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by erBibek** [platformio/platformio-home#2104] opened 2021-01-18 10:54 UTC
PIO Core Call Error: "Platform Manager: Installing freeRTOS\r\n\n\nError: Could not find the package with 'freeRTOS' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment] 2021-01-26 14:40
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:40 UTC
