### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by mamunsyuhada** [platformio/platformio-home#411] opened 2020-02-18 06:06 UTC
PIO Core Call Error: "[Errno 2] No such file or directory: '/Users/mamun/Documents/PlatformIO/Projects/MyProject'"

**Comment by ivankravets** [comment] 2020-02-29 17:21
Duplicate of https://github.com/platformio/platformio-home/issues/408

**Closed by ivankravets** 2020-02-29 17:21 UTC
