### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by thaivuongha** [platformio/platformio-home#297] opened 2020-01-13 10:26 UTC
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\TA QUOC ANH\\\\.platformio\\\\platforms\\\\Arduino_Core_STM32\\\\platform.json'","type":"IOError"}

**Comment by ivankravets** [comment] 2020-02-29 17:21
Duplicate of https://github.com/platformio/platformio-home/issues/408

**Closed by ivankravets** 2020-02-29 17:21 UTC
