### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by rockyanton** [platformio/platformio-home#1798] opened 2020-12-02 18:32 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Losga\\.platformio\\platforms\\ststm32@9.0.0 metadata=PackageMetaData <type=platform name=ststm32 version=9.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by rockyanton** [comment] 2020-12-02 18:33
Solved after program restart

**Comment by ivankravets** [comment] 2021-01-20 13:48
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:48 UTC

**Comment by rockyanton** [comment] 2021-01-25 20:17
Sorry I don't remember, almost 2 months passed.
