### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by gerom76** [platformio/platformio-home#2093] opened 2021-01-16 22:44 UTC
PIO Core Call Error: "The current working directory C:\\Users\\jsycz\\OneDrive - Euvic\\Dokumenty\\PlatformIO\\Projects\\ESP32 test will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\jsycz\\OneDrive - Euvic\\Dokumenty\\PlatformIO\\Projects\\ESP32 test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80200.0\r\nTool Manager: toolchain-xtensa32 @ 2.80200.200827 has been installed!\r\nTool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0\r\nTool Manager: toolchain-esp32ulp @ 1.22851.191205 has been installed!\r\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\r\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\r\nTool Manager: Installing platformio/tool-cmake @ ~3.16.0\r\nTool Manager: tool-cmake @ 3.16.4 has been installed!\r\nTool Manager: Installing platformio/tool-ninja @ ^1.7.0\r\nTool Manager: tool-ninja @ 1.9.0 has been installed!\r\nTool Manager: Installing platformio/tool-mconf @ ~1.4060000.0\r\nTool Manager: tool-mconf @ 1.4060000.20190628 has been installed!\r\nTool Manager: Installing platformio/tool-idf @ ~1.0.1\r\nTool Manager: tool-idf @ 1.0.1 has been installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\r\nPLATFORM: Espressif 32 (2.1.0) > Espressif ESP32 Dev Module\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40100.200827 (4.1.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.30000.201119 (3.0.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200827 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\nCollecting cryptography>=2.1.4\r\n  Using cached cryptography-3.3.1-cp36-abi3-win_amd64.whl (1.5 MB)\r\nCollecting future>=0.15.2\r\n  Downloading future-0.18.2.tar.gz (829 kB)\r\nCollecting pyparsing<2.4.0,>=2.0.3\r\n  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\r\nCollecting cffi>=1.12\r\n  Downloading cffi-1.14.4-cp37-cp37m-win_amd64.whl (178 kB)\r\nCollecting six>=1.4.1\r\n  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)\r\nCollecting pycparser\r\n  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)\r\nBuilding wheels for collected packages: future\r\n  Building wheel for future (setup.py): started\r\n  Building wheel for future (setup.py): finished with status 'done'\r\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=85be56f8863a6098bba3fef36ae1a308555b8d74448e46f73faa32d7c7a6964e\r\n  Stored in directory: c:\\users\\jsycz\\appdata\\local\\pip\\cache\\wheels\\56\\b0\\fe\\4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0\r\nSuccessfully built future\r\nInstalling collected packages: pycparser, six, cffi, pyparsing, future, cryptography\r\nSuccessfully installed cffi-1.14.4 cryptography-3.3.1 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 six-1.15.0\r\nInstalling windows-curses package\r\nProcessing c:\\users\\jsycz\\.platformio\\packages\\framework-espidf\\tools\\kconfig_new\\esp-windows-curses\r\nCollecting windows-curses\r\n  Downloading windows_curses-2.2.0-cp37-cp37m-win_amd64.whl (70 kB)\r\nBuilding wheels for collected packages: esp-windows-curses\r\n  Building wheel for esp-windows-curses (setup.py): started\r\n  Building wheel for esp-windows-curses (setup.py): finished with status 'done'\r\n  Created wheel for esp-windows-curses: filename=esp_windows_curses-0.1-py3-none-any.whl size=1170 sha256=137fae3a06135be082f35c7dfdd1a65ddef9c8d36a0e97a821904216f8295ead\r\n  Stored in directory: c:\\users\\jsycz\\appdata\\local\\pip\\cache\\wheels\\08\\95\\12\\60bfd7282985ab9ac4a38bcb7272a2f823ba47cf564f09d237\r\nSuccessfully built esp-windows-curses\r\nInstalling collected packages: windows-curses, esp-windows-curses\r\nSuccessfully installed esp-windows-curses-0.1 windows-curses-2.2.0\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 355.85 seconds ========================="

**Comment by ivankravets** [comment] 2021-01-20 12:55
Duplicate of https://github.com/platformio/platform-espressif32/issues/470

**Closed by ivankravets** 2021-01-20 12:55 UTC
