### ISSUE TITLE
OS_MAKE_DIRS

### ISSUE THREAD

**Issue by alfarisw** [platformio/platformio-home#437] opened 2020-02-27 05:58 UTC
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\ABAC\\\\Documents\\\\PlatformIO'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment] 2020-02-29 17:00
Duplicate of https://github.com/platformio/platformio-home/issues/408

**Closed by ivankravets** 2020-02-29 17:00 UTC
