### ISSUE TITLE
Could not load platform updates

### ISSUE THREAD

**Issue by erreesse** [platformio/platformio-home#2160] opened 2021-01-23 21:38 UTC
PIO Core Call Error: "b''\n\nError: Unknown development platform 'PackageItem <path=C:\\Users\\utente\\.platformio\\platforms\\atmelavr metadata=PackageMetaData <type=platform name=atmelavr version=3.1.0 spec={'owner': 'platformio', 'id': 8006, 'name': 'atmelavr', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-26 13:00
Duplicate of https://github.com/platformio/platformio-home/issues/2123

**Closed by ivankravets** 2021-01-26 13:00 UTC
