### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by grosdode** [platformio/platformio-home#1695] opened 2020-11-13 07:47 UTC
Hello,
I get the following error: _PIO Core Call Error: "DLL load failed: Die angegebene Prozedur wurde nicht gefunden."_ 

echo %PATH%
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Miniconda3;C:\ProgramData\Miniconda3\Library\mingw-w64\bin;C:\ProgramData\Miniconda3\Library\usr\bin;C:\ProgramData\Miniconda3\Library\bin;C:\ProgramData\Miniconda3\Scripts;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Pico Technology\PicoScope6\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Nordic Semiconductor\nrf5x\bin\;C:\Program Files\LLVM\bin;C:\Python27\Scriptspg4win\..\GnuPG\bin;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Wolfram Research\WolframScript\;C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;C:\Arbeit\emscripten\emsdk;C:\Arbeit\emscripten\emsdk\upstream\emscripten;C:\Arbeit\emscripten\emsdk\node\12.9.1_64bit\bin;C:\Arbeit\emscripten\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64;C:\Arbeit\emscripten\emsdk\java\8.152_64bit\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Go\bin;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Users\dominikg\scoop\shims;c:\gnuarmemb\bin;C:\Program Files (x86)\GNU Tools ARM Embedded\5.4 2016q3\bin;C:\Users\dominikg\AppData\Local\Microsoft\WindowsApps;C:\Users\dominikg\AppData\Local\atom\bin;C:\Users\dominikg\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\SumatraPDF\SumatraPDF.exe;C:\Program Files\serialplot\bin;C:\Users\dominikg\AppData\Local\Programs\Julia\Julia-1.4.0\bin;C:\Users\dominikg\go\bin;C:\Users\dominikg\AppData\Local\Microsoft\WindowsApps;C:\Users\dominikg\.dotnet\tools

echo %PYTHONPATH%
%PYTHONPATH%

python --version
Python 3.7.3

pip --version
pip 20.2.3 from c:\programdata\miniconda3\lib\site-packages\pip (python 3.7)

pip list
Package                        Version
------------------------------ ----------------------
-ip                            19.2.3
-ornado                        6.0.2
alabaster                      0.7.12
appdirs                        1.4.3
arrow                          0.14.2
asn1crypto                     0.24.0
atomicwrites                   1.3.0
attrs                          19.1.0
Babel                          2.7.0
backcall                       0.1.0
behave                         1.2.6
bleach                         3.1.0
bleak                          0.4.3
breathe                        4.13.1
certifi                        2019.3.9
cffi                           1.12.2
chardet                        3.0.4
Click                          7.0
cmsis-pack-manager             0.2.9
colorama                       0.4.1
CommonMark                     0.5.4
conda                          4.6.14
configobj                      5.0.6
crcmod                         1.7
cryptography                   2.6.1
cycler                         0.10.0
decorator                      4.4.0
defusedxml                     0.6.0
docopt                         0.6.2
docutils                       0.15.2
ecdsa                          0.14.1
editdistance                   0.5.3
entrypoints                    0.3
enum-compat                    0.0.2
enum34                         1.1.6
fpdf                           1.7.2
future                         0.18.2
gcovr                          4.2
git-spindle                    3.4.4
github3.py                     0.9.6
gitlint                        0.12.0
idna                           2.8
imagesize                      1.1.0
importlib-metadata             0.23
intelhex                       2.2.1
intervaltree                   3.0.2
ipaddress                      1.0.23
ipykernel                      5.1.0
ipython                        7.5.0
ipython-genutils               0.2.0
ipywidgets                     7.4.2
jedi                           0.13.3
Jinja2                         2.10.1
json5                          0.8.5
jsonschema                     3.0.1
junit2html                     22
jupyter                        1.0.0
jupyter-client                 5.2.4
jupyter-console                6.0.0
jupyter-core                   4.4.0
jupyterlab                     1.2.4
jupyterlab-server              1.0.6
kiwisolver                     1.1.0
libusb1                        1.7.1
lxml                           4.4.2
MarkupSafe                     1.1.1
matplotlib                     3.1.1
menuinst                       1.4.16
milksnake                      0.1.5
mistune                        0.8.4
more-itertools                 7.2.0
nbconvert                      5.5.0
nbformat                       4.4.0
notebook                       5.7.8
nrfutil                        5.2.0
numpy                          1.16.4
packaging                      19.2
paho-mqtt                      1.5.1
pandas                         0.25.1
pandocfilters                  1.4.2
parse                          1.12.1
parse-type                     0.5.2
parso                          0.4.0
pc-ble-driver-py               0.11.4
piccata                        1.0.1
pickleshare                    0.7.5
Pillow                         6.2.1
pip                            20.2.3
plotly                         4.1.0
pluggy                         0.13.1
ply                            3.11
prettytable                    0.7.2
prometheus-client              0.6.0
prompt-toolkit                 2.0.9
protobuf                       3.11.0
py                             1.8.0
pycosat                        0.6.3
pycparser                      2.19
pyelftools                     0.25
pygatt                         4.0.3
pygit2                         0.28.2
Pygments                       2.3.1
pykwalify                      1.7.0
pyocd                          0.23.0
pyOpenSSL                      19.0.0
pyparsing                      2.4.0
PyQt5                          5.13.0
PyQt5-sip                      4.19.17
pyqt5-tools                    5.13.0.1.5
pyrsistent                     0.15.1
pyserial                       3.4
PySide2                        5.11.4a1.dev1546291887
PySocks                        1.6.8
pyspinel                       1.0.0a3
pytest                         5.3.0
python-dateutil                2.8.0
python-dotenv                  0.13.0
pythonnet                      2.4.0
pytz                           2019.2
pyusb                          1.0.2
PyVISA                         1.10.1
PyVISA-py                      0.3.1
pywin32                        223
pywinpty                       0.5.5
pywinusb                       0.4.2
PyYAML                         5.1
pyzmq                          18.0.1
qtconsole                      4.4.3
recommonmark                   0.4.0
requests                       2.21.0
retrying                       1.3.3
ruamel-yaml                    0.15.46
Send2Trash                     1.5.0
setuptools                     41.0.0
six                            1.12.0
snowballstemmer                2.0.0
sortedcontainers               2.1.0
Sphinx                         2.2.1
sphinx-rtd-theme               0.4.3
sphinx-tabs                    1.1.13
sphinxcontrib-applehelp        1.0.1
sphinxcontrib-devhelp          1.0.1
sphinxcontrib-htmlhelp         1.0.2
sphinxcontrib-jsmath           1.0.1
sphinxcontrib-mscgen           0.5
sphinxcontrib-qthelp           1.0.2
sphinxcontrib-serializinghtml  1.1.3
sphinxcontrib-svg2pdfconverter 1.0.1
terminado                      0.8.2
testpath                       0.4.2
tornado                        6.0.3
tqdm                           4.39.0
traitlets                      4.3.2
uritemplate                    3.0.0
uritemplate.py                 3.0.2
urllib3                        1.24.1
virtualenv                     16.7.9
wcwidth                        0.1.7
webencodings                   0.5.1
west                           0.6.3
wheel                          0.33.1
whelk                          2.8.2
widgetsnbextension             3.4.2
win-inet-pton                  1.1.0
wincertstore                   0.2
windows-curses                 2.1.0
wrapt                          1.11.2
zipp                           0.6.0

**Comment by ivankravets** [comment] 2020-12-02 16:08
Duplicate of https://github.com/platformio/platformio-home/issues/1772

**Closed by ivankravets** 2020-12-02 16:08 UTC
