### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by alstrazz** [platformio/platformio-home#2016] opened 2021-01-04 21:39 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\alessandro\\.platformio\\platforms\\espressif8266 metadata=PackageMetaData <type=platform name=espressif8266 version=2.6.2 spec={'owner': 'platformio', 'id': 8008, 'name': 'espressif8266', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:44
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:44 UTC
