### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Polyphe** [platformio/platformio-home#2000] opened 2021-01-02 10:13 UTC
PIO Core Call Error: "The current working directory /Users/Polyphe/Documents/PlatformIO/Projects/Guitar will be used for the project.\n\nThe next files/directories have been created in /Users/Polyphe/Documents/PlatformIO/Projects/Guitar\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'bbcmicrobit_v2'"

**Comment by ivankravets** [comment] 2021-01-26 15:09
Duplicate of https://github.com/platformio/platformio-home/issues/1768

**Closed by ivankravets** 2021-01-26 15:09 UTC
