### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by vortex314** [platformio/platformio-home#1977] opened 2020-12-29 13:50 UTC
PIO Core Call Error: "The current working directory /home/lieven/Documents/PlatformIO/Projects/stm32f401_cm3 will be used for the project.\n\nThe next files/directories have been created in /home/lieven/Documents/PlatformIO/Projects/stm32f401_cm3\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'blackpill_f401ce'"

**Comment by ivankravets** [comment] 2021-01-26 15:09
Duplicate of https://github.com/platformio/platformio-home/issues/1768

**Closed by ivankravets** 2021-01-26 15:09 UTC
