### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by Stormfila** [platformio/platformio-home#2101] opened 2021-01-18 01:49 UTC
PIO Core Call Error: "Platform Manager: Installing firmware\r\n\n\nError: Could not find the package with 'firmware' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment] 2021-01-26 14:37
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:37 UTC
