### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by andygb40** [platformio/platformio-home#1914] opened 2020-12-19 11:12 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\a_g_b\\.platformio\\platforms\\espressif32@2.0.0 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by LennartArendt** [comment] 2020-12-23 12:27
Just had the same problem, just with a different platform, try deleting the platform folder and hit build again. 
For me it installed the platform again and everything worked!

**Comment by ivankravets** [comment] 2021-01-20 13:47
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:47 UTC
