### ISSUE TITLE
FileNotFoundError: Could not initialize project

### ISSUE THREAD

**Issue by huynhmaook** [platformio/platformio-home#408] opened 2020-02-17 06:27 UTC
# Temporary solution

1. Please check that antivirus tools do not block PlatformIO.
2. Try to restart PIO Home/VSCode.

------

Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\Administrator\\\\Documents\\\\PlatformIO'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment] 2021-01-26 14:34
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Closed by ivankravets** 2021-01-26 14:34 UTC
Labels: help wanted, known issue
