### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by FlorencioEder** [platformio/platformio-home#1900] opened 2020-12-17 00:47 UTC
PIO Core Call Error: "The current working directory C:\\Users\\eder_\\Desktop\\Edinho\\Tamandutech\\Podolski\\Podolski ESP32 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\eder_\\Desktop\\Edinho\\Tamandutech\\Podolski\\Podolski ESP32\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80200.0\r\nTool Manager: toolchain-xtensa32 @ 2.80200.200827 has been installed!\r\nTool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0\r\nTool Manager: toolchain-esp32ulp @ 1.22851.191205 has been installed!\r\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\r\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\r\nTool Manager: Installing platformio/tool-cmake @ ~3.16.0\r\nTool Manager: tool-cmake @ 3.16.4 has been installed!\r\nTool Manager: Installing platformio/tool-ninja @ ^1.7.0\r\nTool Manager: tool-ninja @ 1.9.0 has been installed!\r\nTool Manager: Installing platformio/tool-mconf @ ~1.4060000.0\r\nTool Manager: tool-mconf @ 1.4060000.20190628 has been installed!\r\nTool Manager: Installing platformio/tool-idf @ ~1.0.1\r\nTool Manager: tool-idf @ 1.0.1 has been installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html\r\nPLATFORM: Espressif 32 (2.0.0) > DOIT ESP32 DEVKIT V1\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40100.200827 (4.1.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200827 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\nCollecting cryptography>=2.1.4\r\n  Downloading cryptography-3.3.1-cp36-abi3-win_amd64.whl (1.5 MB)\r\nCollecting future>=0.15.2\r\n  Downloading future-0.18.2.tar.gz (829 kB)\r\nCollecting pyparsing<2.4.0,>=2.0.3\r\n  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\r\nCollecting cffi>=1.12\r\n  Downloading cffi-1.14.4-cp37-cp37m-win_amd64.whl (178 kB)\r\nCollecting six>=1.4.1\r\n  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)\r\nCollecting pycparser\r\n  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)\r\nBuilding wheels for collected packages: future\r\n  Building wheel for future (setup.py): started\r\n  Building wheel for future (setup.py): finished with status 'done'\r\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491062 sha256=de2a519c4be28d9809a39e9a1364c9e5f781b56109bc9894f38b33f996a17e2d\r\n  Stored in directory: c:\\users\\eder_\\appdata\\local\\pip\\cache\\wheels\\56\\b0\\fe\\4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0\r\nSuccessfully built future\r\nInstalling collected packages: pycparser, cffi, six, cryptography, future, pyparsing\r\nSuccessfully installed cffi-1.14.4 cryptography-3.3.1 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 six-1.15.0\r\nWARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.\r\nYou should consider upgrading via the 'c:\\users\\eder_\\.platformio\\penv\\scripts\\python.exe -m pip install --upgrade pip' command.\r\nInstalling windows-curses package\r\nProcessing c:\\users\\eder_\\.platformio\\packages\\framework-espidf\\tools\\kconfig_new\\esp-windows-curses\r\nCollecting windows-curses\r\n  Downloading windows_curses-2.2.0-cp37-cp37m-win_amd64.whl (70 kB)\r\nBuilding wheels for collected packages: esp-windows-curses\r\n  Building wheel for esp-windows-curses (setup.py): started\r\n  Building wheel for esp-windows-curses (setup.py): finished with status 'done'\r\n  Created wheel for esp-windows-curses: filename=esp_windows_curses-0.1-py3-none-any.whl size=1175 sha256=cd48752d48a00af14a04ca4a7f8169bd0777e65bea8c4bca91b119c31bf11232\r\n  Stored in directory: c:\\users\\eder_\\appdata\\local\\pip\\cache\\wheels\\9c\\5a\\71\\14f592313d0587f3132240c84e01da3eb0b0e17a5388fea3b9\r\nSuccessfully built esp-windows-curses\r\nInstalling collected packages: windows-curses, esp-windows-curses\r\nSuccessfully installed esp-windows-curses-0.1 windows-curses-2.2.0\r\nWARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.\r\nYou should consider upgrading via the 'c:\\users\\eder_\\.platformio\\penv\\scripts\\python.exe -m pip install --upgrade pip' command.\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 500.93 seconds ========================="

**Comment by ivankravets** [comment] 2021-01-20 12:55
Duplicate of https://github.com/platformio/platform-espressif32/issues/470

**Closed by ivankravets** 2021-01-20 12:55 UTC
