### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by ruban-ruslan** [platformio/platformio-home#430] opened 2020-02-25 10:08 UTC
PIO Core Call Error: "Platform C:\\Users\\Ruslan\\.platformio\\platforms\\espressif32\r\n--------\r\n\n\nError: Traceback (most recent call last):\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 410, in platform_update\r\n    pm.update(platform, only_packages=only_packages, only_check=only_check)\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 143, in update\r\n    p = PlatformFactory.newPlatform(pkg_dir)\r\n  File \"C:\\Users\\Ruslan\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 249, in newPlatform\r\n    name = pm.load_manifest(platform_dir)[\"name\"]\r\nTypeError: 'NoneType' object is not subscriptable\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment] 2020-02-29 17:10
Duplicate of https://github.com/platformio/platformio-home/issues/197

**Closed by ivankravets** 2020-02-29 17:10 UTC
