### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by n9wxu** [platformio/platformio-home#429] opened 2020-02-24 22:54 UTC
PIO Core Call Error: "The current working directory /Users/joejulicher/Documents/PlatformIO/Projects/sam_test will be used for the project.\n\nThe next files/directories have been created in /Users/joejulicher/Documents/PlatformIO/Projects/sam_test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'sparkfun_samd21_proRF'"

**Comment by ivankravets** [comment] 2020-02-29 17:17
Duplicate of https://github.com/platformio/platformio-home/issues/155

**Closed by ivankravets** 2020-02-29 17:17 UTC
