### ISSUE TITLE
Could not import Arduino project

### ISSUE THREAD

**Issue by psychotik2k3** [platformio/platformio-home#343] opened 2020-01-27 19:58 UTC
PIO Core Call Error: "The current working directory C:\\Users\\sebas\\OneDrive\\Documents\\PlatformIO\\Projects\\200127-205752-lora32u4II will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\sebas\\OneDrive\\Documents\\PlatformIO\\Projects\\200127-205752-lora32u4II\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'lora32u4II'"

**Comment by ivankravets** [comment] 2020-02-29 17:17
Duplicate of https://github.com/platformio/platformio-home/issues/155

**Closed by ivankravets** 2020-02-29 17:17 UTC
