### ISSUE TITLE
Could not import Arduino project

### ISSUE THREAD

**Issue by MadhavanBinu** [platformio/platformio-home#255] opened 2019-12-28 08:40 UTC
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\binum\\\\Documents\\\\PlatformIO\\\\Projects\\\\191228-140808-uno'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment] 2020-02-29 16:59
Duplicate of https://github.com/platformio/platformio-home/issues/408

**Closed by ivankravets** 2020-02-29 16:59 UTC
