### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by picard12** [platformio/platformio-home#377] opened 2020-02-08 06:44 UTC
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/platformio/__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/platformio/commands/platform.py\", line 219, in platform_list\n    manifest[\"__pkg_dir\"], with_boards=False, expose_packages=False\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/platformio/commands/platform.py\", line 72, in _get_installed_platform_data\n    p = PlatformFactory.newPlatform(platform)\n  File \"/home/christian/.platformio/penv/lib64/python3.6/site-packages/platformio/managers/platform.py\", line 253, in newPlatform\n    cls.get_clsname(name),\nAttributeError: module 'platformio.managers.platform.atmelavr' has no attribute 'AtmelavrPlatform'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment] 2020-02-29 17:10
Duplicate of https://github.com/platformio/platformio-home/issues/197

**Closed by ivankravets** 2020-02-29 17:10 UTC
