### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by sbh04101989** [platformio/platformio-home#2089] opened 2021-01-16 20:36 UTC
PIO Core Call Error: "Platform Manager: Installing Foo\r\n\n\nError: Could not find the package with 'Foo' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment] 2021-01-26 14:37
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:37 UTC
