### ISSUE TITLE
Error occurred while requesting content from https://dl.registry.platformio.org/examples/07/0d/816641b8a2135cdfcfd8539db8957c0c766d95a8c2c616e56a91a9eb1d7d/TalkingClockI2S.ino

### ISSUE THREAD

**Issue by Hassan-Ahmadi** [platformio/platformio-home#2071] opened 2021-01-12 17:07 UTC
HTTPSConnectionPool(host='dl.registry.platformio.org', port=443): Max retries exceeded with url: /examples/07/0d/816641b8a2135cdfcfd8539db8957c0c766d95a8c2c616e56a91a9eb1d7d/TalkingClockI2S.ino (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029EA3B0AC08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by ivankravets** [comment] 2021-01-26 17:57
Duplicate of https://github.com/platformio/platformio-core/issues/1348

**Closed by ivankravets** 2021-01-26 17:57 UTC
