### ISSUE TITLE
Could not load platform updates

### ISSUE THREAD

**Issue by ApocalypticManD** [platformio/platformio-home#2061] opened 2021-01-10 22:56 UTC
PIO Core Call Error: "b''\n\nError: Unknown development platform 'PackageItem <path=C:\\Users\\Dino\\.platformio\\platforms\\atmelavr metadata=PackageMetaData <type=platform name=atmelavr version=3.1.0 spec={'owner': 'platformio', 'id': 8006, 'name': 'atmelavr', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:42
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:42 UTC
