### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by drorfromthenegev** [platformio/platformio-home#175] opened 2019-12-12 06:53 UTC
I tried to create a project for Thingy52, with an up-to-dat platformio-core, and got this result:

PIO Core Call Error: "The current working directory C:\\Users\\Dror\\Documents\\PlatformIO\\Projects\\GGGG will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Dror\\Documents\\PlatformIO\\Projects\\GGGG\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Unknown board ID 'thingy_52'"

**Comment by ivankravets** [comment] 2020-02-29 17:16
Duplicate of https://github.com/platformio/platformio-home/issues/155

**Closed by ivankravets** 2020-02-29 17:16 UTC
