### ISSUE TITLE
Could not load platform updates

### ISSUE THREAD

**Issue by RockyBalBoa1961** [platformio/platformio-home#2014] opened 2021-01-04 12:53 UTC
PIO Core Call Error: "b''\n\nError: Unknown development platform 'PackageItem <path=C:\\Users\\marky\\.platformio\\platforms\\ststm32@10.0.1 metadata=PackageMetaData <type=platform name=ststm32 version=10.0.1 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:44
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:44 UTC
