### ISSUE TITLE
DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Tianxiaomo** [platformio/platformio-home#1623] opened 2020-11-02 15:21 UTC
PIO Core Call Error: "DLL load failed: 找不到指定的程序。"

**Comment by ivankravets** [comment] 2020-11-03 13:39
Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type 
```
pio system info
```

Please share the output here.

**Comment by ivankravets** [comment] 2020-12-02 16:08
Duplicate of https://github.com/platformio/platformio-home/issues/1772

**Closed by ivankravets** 2020-12-02 16:08 UTC
Labels: help wanted
