### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by Hilden0408** [platformio/platformio-home#2008] opened 2021-01-03 21:33 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Hilde\\.platformio\\platforms\\nxplpc-arduino-lpc176x metadata=PackageMetaData <type=platform name=nxplpc-arduino-lpc176x version=0.1.3 spec={'owner': None, 'id': None, 'name': 'pio-nxplpc-arduino-lpc176x', 'requirements': None, 'url': 'https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip'}'"

**Comment by ivankravets** [comment] 2021-01-20 13:44
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:44 UTC
