### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by gtbowden** [platformio/platformio-home#1641] opened 2020-11-06 03:51 UTC
PIO Core Call Error: "DLL load failed: The specified procedure could not be found."

Creating new project, chose board
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8

Same error after uninstalling platformIO and reinstalling.

**Comment by ivankravets** [comment] 2020-12-02 16:08
Duplicate of https://github.com/platformio/platformio-home/issues/1772

**Closed by ivankravets** 2020-12-02 16:08 UTC
