### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by luruiwu** [platformio/platformio-home#212] opened 2019-12-24 06:56 UTC
PIO Core Call Error: "The current working directory C:\\Users\\Administrator\\Documents\\PlatformIO\\Projects\\stm32F_6 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Administrator\\Documents\\PlatformIO\\Projects\\stm32F_6\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing genericSTM32F103ZE (framework: cmsis; board: genericSTM32F103ZE; platform: ststm32)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing framework-cmsis @ ~1.40300.0\r\nframework-cmsis @ 1.40300.0 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'genericSTM32F103ZE'\r\n========================= [FAILED] Took 13.23 seconds ========================="

**Comment by ivankravets** [comment] 2020-02-29 17:17
Duplicate of https://github.com/platformio/platformio-home/issues/155

**Closed by ivankravets** 2020-02-29 17:17 UTC
