### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by bennybubble** [platformio/platformio-home#1980] opened 2020-12-29 19:54 UTC
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\antoon\\.platformio\\platforms\\espressif32 metadata=PackageMetaData <type=platform name=espressif32 version=2.1.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment] 2021-01-20 13:44
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Closed by ivankravets** 2021-01-20 13:44 UTC
