### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by github77s** [platformio/platformio-home#1775] opened 2020-11-29 03:04 UTC
PIO Core Call Error: "DLL load failed: The specified procedure could not be found."

When I click on Updates within the Libraries tab I get the same error multiple times.  I get a spinning loading symbol but nothing ever happens.  I just installed it today and checked for updates and it says I have the latest version of both Visual Studio Code and PlatformIO.

**Comment by ivankravets** [comment] 2020-12-02 16:09
Duplicate of https://github.com/platformio/platformio-home/issues/1772

**Closed by ivankravets** 2020-12-02 16:09 UTC
