### ISSUE TITLE
Internal Store Exception

### ISSUE THREAD

**Issue by jmpuch** [platformio/platformio-home#378] opened 2020-02-09 08:36 UTC
TypeError: Object.fromEntries is not a function
    at mapPropsToFields (http://127.0.0.1:8010/main.a07928561c28253026d2.min.js:1:312006)
    at t.getInitialState (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:49:65683)
    at new t (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:19:335598)
    at xi (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:57:51168)
    at $a (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:57:67956)
    at xc (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:57:105945)
    at Pl (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:57:90235)
    at El (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:57:90160)
    at Ml (http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:57:87500)
    at http://127.0.0.1:8010/vendor.c2b02c04cda4b5d41dcb.min.js:57:45830

**Comment by ivankravets** [comment] 2020-02-29 15:32
Duplicate of https://github.com/platformio/platformio-home/issues/181

**Closed by ivankravets** 2020-02-29 15:32 UTC
