### ISSUE TITLE
Libraries: Stats

### ISSUE THREAD

**Issue by ArtofWar-dev** [platformio/platformio-home#2161] opened 2021-01-23 23:04 UTC
PIO Core Call Error: "Error: Traceback (most recent call last):\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\r\n    timeout=timeout\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 859, in urlopen\r\n    **response_kw\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 859, in urlopen\r\n    **response_kw\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 859, in urlopen\r\n    **response_kw\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 836, in urlopen\r\n    retries = retries.increment(method, url, response=response, _pool=self)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 573, in increment\r\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\r\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.registry.platformio.org', port=443): Max retries exceeded with url: /v2/lib/stats (Caused by ResponseError('too many 502 error responses'))\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib\\command.py\", line 538, in lib_stats\r\n    result = regclient.fetch_json_data(\"get\", \"/v2/lib/stats\", cache_valid=\"1h\")\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\platformio\\clients\\http.py\", line 144, in fetch_json_data\r\n    response = self.send_request(method, path, **kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 73, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\platformio\\clients\\http.py\", line 123, in send_request\r\n    return getattr(self._session, method)(path, **kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\requests\\sessions.py\", line 555, in get\r\n    return self.request('GET', url, **kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\platformio\\clients\\http.py\", line 62, in request\r\n    method, urljoin(self.base_url, url), *args, **kwargs\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\r\n    resp = self.send(prep, **send_kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\r\n    r = adapter.send(request, **kwargs)\r\n  File \"C:\\Users\\ArtofWar\\.platformio\\penv\\lib\\site-packages\\requests\\adapters.py\", line 507, in send\r\n    raise RetryError(e, request=request)\r\nrequests.exceptions.RetryError: HTTPSConnectionPool(host='api.registry.platformio.org', port=443): Max retries exceeded with url: /v2/lib/stats (Caused by ResponseError('too many 502 error responses'))\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment] 2021-01-26 17:57
Duplicate of https://github.com/platformio/platformio-core/issues/1348

**Closed by ivankravets** 2021-01-26 17:57 UTC
