### ISSUE TITLE
Ne pouvait pas installer la plate-forme

### ISSUE THREAD

**Issue by EDOL12** [platformio/platformio-home#2145] opened 2021-01-22 13:03 UTC
PIO Core Call Error: "Platform Manager: Installing MKS_GEN_13_h\r\n\n\nError: Could not find the package with 'MKS_GEN_13_h' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment] 2021-01-26 14:36
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:36 UTC
