### ISSUE TITLE
Internal Store Exception

### ISSUE THREAD

**Issue by Pythonaire** [platformio/platformio-home#29] opened 2019-10-29 13:24 UTC
TypeError: Cannot read property 'map' of undefined
    at t.value (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:18:213524)
    at Zi (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:70772)
    at Ji (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:70567)
    at Ds (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:105897)
    at kl (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:90221)
    at Rl (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:90146)
    at El (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:87486)
    at http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:45816
    at t.unstable_runWithPriority (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:42:3465)
    at Ka (http://127.0.0.1:8013/b53d63f92df2c62861fd.min.js:34:45525)

**Comment by ivankravets** [comment] 2019-11-01 15:51
Duplicate of https://github.com/platformio/platformio-home/issues/23

**Closed by ivankravets** 2019-11-01 15:51 UTC
