### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by spierepf** [platformio/platformio-home#1816] opened 2020-12-05 01:03 UTC
PIO Core Call Error: "The current working directory /home/peter/Nextcloud/PlatformIO/Projects/ESP32 Bluetooth Headset will be used for the project.\n\nThe next files/directories have been created in /home/peter/Nextcloud/PlatformIO/Projects/ESP32 Bluetooth Headset\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing lolin_d32_pro (platform: espressif32; board: lolin_d32_pro; framework: espidf)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin_d32_pro.html\nPLATFORM: Espressif 32 (2.1.0) > WEMOS LOLIN D32 PRO\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40100.200827 (4.1.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.30000.201119 (3.0.0) \n - tool-ninja 1.7.1 \n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \n - toolchain-xtensa32 2.80200.200827 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nLooking in indexes: https://pf.spierenburg:****@artifactory.navblue.tech/artifactory/api/pypi/pypi/simple\nWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='artifactory.navblue.tech', port=443): Read timed out. (read timeout=15)\",)': /artifactory/api/pypi/pypi/simple/cryptography/\nWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='artifactory.navblue.tech', port=443): Read timed out. (read timeout=15)\",)': /artifactory/api/pypi/pypi/simple/cryptography/\nWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='artifactory.navblue.tech', port=443): Read timed out. (read timeout=15)\",)': /artifactory/api/pypi/pypi/simple/cryptography/\nWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='artifactory.navblue.tech', port=443): Read timed out. (read timeout=15)\",)': /artifactory/api/pypi/pypi/simple/cryptography/\nWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='artifactory.navblue.tech', port=443): Read timed out. (read timeout=15)\",)': /artifactory/api/pypi/pypi/simple/cryptography/\nERROR: Could not find a version that satisfies the requirement cryptography>=2.1.4 (from versions: none)\nERROR: No matching distribution found for cryptography>=2.1.4\n*** Error 1\nError: Detected a whitespace character in project paths.\n========================= [FAILED] Took 104.84 seconds ========================="

**Comment by ivankravets** [comment] 2021-01-20 12:55
Duplicate of https://github.com/platformio/platform-espressif32/issues/470

**Comment by ivankravets** [comment] 2021-01-20 12:55
Duplicate of https://github.com/platformio/platform-espressif32/issues/470

**Closed** 2021-01-20 12:56 UTC
