### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by matteocutugno** [platformio/platformio-home#395] opened 2020-02-13 10:28 UTC
PIO Core Call Error: "The current working directory /home/matteo/Documents/PlatformIO/Projects/200213-112654-INS will be used for the project.\n\nThe next files/directories have been created in /home/matteo/Documents/PlatformIO/Projects/200213-112654-INS\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'openIMU300'"

**Comment by ivankravets** [comment] 2020-02-29 17:17
Duplicate of https://github.com/platformio/platformio-home/issues/155

**Closed by ivankravets** 2020-02-29 17:17 UTC
