### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by shukan2007** [platformio/platformio-home#2081] opened 2021-01-15 01:38 UTC
PIO Core Call Error: "Platform Manager: Installing Advanced platform installationa\r\n\n\nError: Could not find the package with 'Advanced platform installationa' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment] 2021-01-26 14:37
Duplicate of https://github.com/platformio/platformio-home/issues/2144

**Closed by ivankravets** 2021-01-26 14:37 UTC
